image: quay.io/tike/alpine-oc-node

variables:
    npm_config_cache: '$CI_PROJECT_DIR/.npm'
    PROJECT_NAME: 'imitaatiopeli-db'
    PROJECT_VERSION: '1.0.0'

stages:
    - setup
    - test
    - build

.dependencies_cache:
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - .npm
        policy: pull

# Define the process for setup stage
build:
    stage: setup
    image: node:22-alpine
    tags:
        - ohtu-build-4
    script:
        - npm ci
    extends: .dependencies_cache
    cache:
        policy: pull-push
    artifacts:
        expire_in: 1h
        paths:
            - node_modules

# Define the process for test stage
test:
    stage: test
    image: node:22-alpine
    services:
        - postgres:16-alpine
    variables:
        variables:
        POSTGRES_DB: ${DATABASE}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${PASSWORD}
        POSTGRES_HOST_AUTH_METHOD: trust
    tags:
        - ohtu-build-4
    script:
        - npm run coverage
    coverage: /All files\s*\|\s*([\d\.]+)/
    artifacts:
        name: imitaatiopeli-coverage
        paths:
            - coverage
        expire_in: 1 hour
    extends: .dependencies_cache
