UPDATE GAME_CONFIGURATION SET
  AI_PROMPT = $1,
  GAME_NAME = $2,
  THEME_DESCRIPTION = $3,
  LANGUAGE_USED = $4,
  INSTRUCTIONS_FOR_PLAYERS = $5,
  IS_RESEARCH_GAME = $6,
  RESEARCH_DESCRIPTION = $7,
  LANGUAGE_MODEL = $8,
  MODEL_TEMPERATURE = $9,
  ANSWER_RANDOMIZATION = $11
WHERE
  CONFIG_ID = $10
RETURNING *;
