
INSERT INTO player (PLAYER_ID, IS_PRETENDER, GAME_ID, CREATED_AT)
VALUES($1, $2, $3, $4)
    ON CONFLICT (player_id) DO UPDATE SET
    PLAYER_ID = $1, IS_PRETENDER = $2, GAME_ID = $3, CREATED_AT = $4 RETURNING *
